# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import shops.models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='theme',
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=shops.models.upload_location, width_field='width_field'),
        ),
    ]
