# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import shops.models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20180118_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shops.models.upload_location),
        ),
    ]
