# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20180118_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
